config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'tweets#index'

  resources :tweets, except: [:new] do
    resources :comments, only: [:new, :create]

    collection do
      get :view_followers
      get :view_followees
      get :search_tag
    end

    member do
      post :like
      delete :unlike
    end
  end

  resources :profile, param: :username, only: [:show] do
    member do
      resources :followings, only: [:create, :destroy]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :tweet, foreign_key: 'tweet_id'
  belongs_to :user

  validates :text, length: { maximum: 140 }
  validates :text, presence: true

end

app/models/following.rb
class Following < ApplicationRecord

  belongs_to :follower, class_name: 'User'
  belongs_to :followee, class_name: 'User'

end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :tweet
  belongs_to :user
  
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_and_belongs_to_many :tweets

  validates :text, presence: true

end

app/models/tweet.rb
class Tweet < ApplicationRecord

  validates :text, length: { maximum: 140 }
  validates :text, presence: true

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_and_belongs_to_many :tags

end

app/models/user.rb
class User < ApplicationRecord

  mount_uploader :avatar, AvatarUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_integrity_of :avatar
  validates_processing_of :avatar

  has_many :tweets
  has_many :comments
  has_many :likes

  has_many :is_following, class_name: 'Following', foreign_key: 'follower_id'
  has_many :is_followed, class_name: 'Following', foreign_key: 'followee_id'

  def likes?(tweet, user)
    @like = Like.find_by(tweet_id: tweet.id, user: user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :first_name, :last_name, :password, :password_confirmation, :remember_me, :avatar, :avatar_cache, :remove_avatar]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @tweet = Tweet.find(params[:tweet_id])
    @comment = Comment.new
  end

  def create
    @tweet = Tweet.find(params[:tweet_id])
    @comment = current_user.comments.build(comment_params.merge(tweet: @tweet))

    if @comment.save
      redirect_to tweet_path(@tweet)
    else
      render :new
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text, :tweet_id)
  end

end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController

  def create
    @follower = current_user
    @followee = User.find_by(username: params[:username])

    if @followee != @follower
      @following = @follower.is_following.build(followee: @followee)
      @following.save
    end

    respond_to do |format|
      format.html { redirect_to profile_path(@followee.username) }
      format.js
    end
  end

  def destroy
    @followee = User.find_by(username: params[:username])
    @following = Following.find_by(follower_id: current_user.id, followee_id: @followee.id)
    @following.destroy
    redirect_to profile_path(@followee.username)
  end

end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController

  def show
    @user = User.find_by(username: params[:username])
    @tweets = Tweet.where(user_id: @user.id)
    @following = Following.find_by(followee_id: @user.id, follower_id: current_user.id)
    @user_followers = Following.where(followee: @user)
    @user_followees = Following.where(follower: @user)
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def show
    @user = User.find(params[:id])
    @tweets = Tweet.where(user_id: @user.id)
    @following = Following.find_by(followee_id: @user.id, follower_id: current_user.id)
    @user_followers = Following.where(followee: @user)
    @user_followees = Following.where(follower: @user)
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :authenticate_user!

  def index
    @tweets = Tweet.all
    @users = User.all
    @tweet = Tweet.new
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def create
    @tweets = Tweet.all
    @users = User.all
    @tweet = current_user.tweets.build(tweet_params)

    identify_tags
    sanitize_tags

    respond_to do |format|
      if @tweet.save
        @tags.each do |tag|
          new_tag = @tweet.tags.create(text: tag)
        end
        format.html { redirect_to tweets_path }
        format.js
      else
        format.html { render :index }
        format.js
      end
    end

  end

  def edit
    @tweet = Tweet.find(params[:id])

    if current_user.id != @tweet.user.id
      redirect_to tweets_path
    end
  end

  def update
    @tweet = Tweet.find(params[:id])
    @tweet.update(tweet_params)
    redirect_to tweets_path
  end

  def destroy
    @tweets = Tweet.all
    @tweet = Tweet.find(params[:id])
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_path }
      format.js
    end
  end

  def view_followers
    @followers = Following.where(follower_id: current_user.id)
  end

  def view_followees
    @followees = Following.where(followee_id: current_user.id)
  end

  def search_tag
    @tag = Tag.find_by(text: params[:format])
    @tweets = @tag.tweets
  end

  def like
    @tweets = Tweet.all
    @users = User.all

    @tweet = Tweet.find(params[:id])
    @like = current_user.likes.build(tweet: @tweet)
    @like.save

    respond_to do |format|
      format.html { redirect_to tweets_path }
      format.js
    end
  end

  def unlike
    @tweets = Tweet.all
    @users = User.all

    @like = Like.find_by(tweet: params[:id], user: current_user)
    @like.destroy

    respond_to do |format|
      format.html { redirect_to tweets_path }
      format.js
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:text)
  end

  def comment_params
    params.require(:comment).permit(:text, :tweet_id)
  end

  def identify_tags
    @body = params[:tweet][:text]
    @tags = []
    @body << ' '

    while @body.include?('#')
      tag_start = @body.rindex('#')
      @body.insert(tag_start,' ')
      tag_start += 1
      tag_end = @body.index(' ',tag_start)
      tag_length = tag_end - tag_start

      @tags << @body.slice!(tag_start, tag_length)
    end
    @tags.reverse!
  end

  def sanitize_tags
    @tags.each do |tag|
      tag.delete!('#')
      tag.upcase
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/comments/_commentform.html.erb
<%= simple_form_for @comment, url: { action: "create" } do |f| %>

  <%= f.text_area :text, label: false, class: "form-control" %>

  <%= f.submit class: "btn btn-primary btn-lg btn-group-justified" %>

<% end %>

app/views/comments/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 well">
      <%= render partial: 'commentform' %>

    </div>
  </div>
</div>

app/views/followings/_follow_button.erb
<% if current_user != @user %>
  <% if @following %>
    <%= button_to 'Unfollow user', following_path(@user), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= button_to 'Follow user', followings_path(@user), method: :post, class: 'btn btn-default' %>
  <% end %>
<% end %>

app/views/followings/create.js.erb
$('#follow-button-container').html("<%= j render partial: 'follow_button' %>")

app/views/followings/destroy.js.erb
$('#follow-button-container').html("<%= j render partial: 'follow_button' %>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitterclone</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body id="main-pane">
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">TwitterClone Home</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'Users you\'re following', view_followers_tweets_path, class: 'navbar-link' %></li>
          <li><%= link_to 'Your followers', view_followees_tweets_path, class: 'navbar-link' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Logged in as <strong><%= current_user.email %></strong><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Edit profile', edit_user_registration_path, method: :get %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %></li>
          <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link' %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>

<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>
</body>
</html>

app/views/profiles/show.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-2 well">
      <h3>User stats</h3>
      <strong><%= @user_followers.count %> followers</strong>
      <% @user_followers.each do |follower| %>
        <%= link_to follower.follower.email, profile_path(follower.follower) %> <br/>
      <% end %>
      <br/>
      <strong>Following <%= @user_followees.count %> users</strong>
      <% @user_followees.each do |followee| %>
        <%= link_to followee.followee.email, profile_path(followee.followee) %> <br/>
      <% end %>

    </div>

    <div class="col-xs-12 col-md-6 col-md-offset-1 well">

      <h1>User: <%= @user.email %></h1>

      <div id="follow-button-container">
        <%= render partial: 'follow_button' %>
      </div>

      <h2>Tweets:</h2>

      <% @tweets.each do |tweet| %>
        <div class="well">
          <strong><%= tweet.text %><br/></strong>
          tweeted on <%= tweet.created_at %>
        </div>

      <% end %>

    </div>
  </div>
</div>

app/views/tweets/_commentlist.html.erb
<% @tweet.comments.order('created_at DESC').each do |comment| %>
  <div class="well">
    <strong><%= comment.text %></strong> <br/><br/>
    posted by <%= link_to comment.user.email, profile_path(comment.tweet.user) %> on <%= comment.updated_at %>
  </div>
<% end %>

app/views/tweets/_tweetform.html.erb
<%= simple_form_for @tweet, remote: true, html: { id: 'new-tweet-form' } do |f| %>
    <%= f.text_area :text, label: false, class: "form-control" %>
    <%= f.submit class: "btn btn-primary btn-lg btn-group-justified", id: "create-tweet-btn" %>
<% end %>

app/views/tweets/_tweetlist.html.erb
<% @tweets.order('created_at DESC').each do |tweet| %>
   <div class="well">
     <div class="row">
       <div class="col-md-3">
         <% if tweet.user.avatar.url.present? %>
         <%= image_tag tweet.user.avatar.url, size: "100x100", class: "img-circle" %>
         <% else %>
         <!-- <%= image_tag "default.jpg", size: "100x100", class: "img-circle" %> -->
         <% end %>

         <%= link_to tweet.user.username, profile_path(tweet.user.username), class: "center-block" %>
       </div>
       <div class="col-md-9">

         <h2> <%= tweet.text %> </h2>

         Likes: <%= tweet.likes.count %> Tag:<% tweet.tags.map(&:text).each do |tag| %>
          <%= link_to ' #' + tag, search_tag_tweets_path(tag) %>
         <% end %> <br/>

         Posted on <%= tweet.updated_at %> <br/>


       </div>
     </div>

      <div class="btn-group btn-group-justified" role="group" aria-label="...">

        <%= link_to tweet_path(tweet) do %> <button type="button" class="btn btn-default"><%= tweet.comments.count %> <%= tweet.comments.count == 1 ? 'reply' : 'replies' %></button> <% end %>

        <% if current_user.id == tweet.user.id %>
          <%= link_to edit_tweet_path(tweet) do %> <button type="button" class="btn btn-default">Edit</button> <% end %>
          <%= link_to tweet_path(tweet), method: :delete, remote: true do %> <button type="button" class="btn btn-danger pull-right">Delete</button> <% end %>
          <!-- , data: { confirm: "Are you sure you wish to permanently delete this tweet?" } %> -->
        <% else %>
          <% if current_user.likes?(tweet, current_user) %>
            <%= link_to unlike_tweet_path(tweet), method: :delete, remote: true do %> <button type="button" class="btn btn-danger">You liked this! Unlike?</button> <% end %>
          <% else %>
            <%= link_to like_tweet_path(tweet), method: :post, remote: true do %> <button type="button" class="btn btn-success">Like this tweet</button> <% end %>
          <% end %>
        <% end %>




      </div>

  </div>
  <br/>
<% end %>

app/views/tweets/create.js.erb
if("<%= @tweet.id %>") {
  $("#tweet-list").html("<%= j render partial: 'tweetlist' %>");
  $("#new-tweet-form").children("#tweet_text").val("");
} else {
  $("#new-tweet-form-container").html("<%= j render partial: 'tweetform' %>");
}

app/views/tweets/destroy.js.erb
$("#tweet-list").html("<%= j render partial: 'tweetlist' %>");

app/views/tweets/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      
      <%= render partial: 'tweetform' %>

    </div>
  </div>
</div>

app/views/tweets/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 well">
      <h1>Try Tweeting!</h1>
      <div id='new-tweet-form-container'>
        <%= render partial: 'tweetform' %>
      </div>

    </div>
  </div>
</div>


<div class="container">
  <div class="row">
    <div id="tweet-list" class="col-md-6 col-md-offset-3 well">
      <%= render partial: 'tweetlist' %>
    </div>
  </div>
</div>

<div>
  <h2>Registered Users:</h2>
  <% @users.each do |user| %>
    <%= link_to user.username, profile_path(user) %>
    <br/>
  <% end %>
</div>

app/views/tweets/like.js.erb
$("#tweet-list").html("<%= j render partial: 'tweetlist' %>")

app/views/tweets/new.html.erb
<%= form_for @tweet, :url => tweets_path do |f| %>
  <%= f.label :text, "Text" %>
  <%= f.text_area :text %>

  <%= f.submit "Create tweet" %>
<% end %>

app/views/tweets/search_tag.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 well">

      <h1>#<%= @tag.text %></h2>

        <div class="well">
          
          <% @tweets.each do |tweet| %>
          <h2> <%= tweet.text %> </h2>

          <% tweet.tags.map(&:text).each do |tag| %>
          <%= link_to ' #' + tag, search_tag_tweets_path(tag) %>
          <% end %> <br/>

          tweeted by <%= link_to tweet.user.username, profile_path(tweet.user.username) %>
          at <%= tweet.updated_at %> <br/>
          <% end %>

        </div>

    </div>
  </div>
</div>

app/views/tweets/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 well">

      <div class="well">
        <h1><%= @tweet.text %></h1>
        tweeted by <%= link_to @tweet.user.email, profile_path(@tweet.user) %> at <%= @tweet.updated_at %>
      </div>

      <div class="well">
        <h3>Replies:</h3>
        <%= render partial: 'commentlist' %>

        <%= button_to "Add a reply", new_tweet_comment_path(@tweet), method: :get, class: "btn btn-default" %>

      </div>

    </div>
  </div>
</div>

app/views/tweets/unlike.js.erb
$("#tweet-list").html("<%= j render partial: 'tweetlist' %>")

app/views/tweets/view_followees.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 well">
      <h1>Latest tweets by users following you</h1>

      <% @followees.each do |followee| %>
        <div class="well">
          <h2><%= followee.follower.username %></h2>

          <div class="well">
            <h3><%= followee.follower.tweets.last.text %></h3>
            tweeted on <%= followee.follower.tweets.last.created_at %>

          </div>
        </div>

      <% end %>

    </div>
  </div>
</div>

app/views/tweets/view_followers.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 well">
      <h1>Latest tweets by users you are following</h1>

      <% @followers.each do |follower| %>
        <div class="well">
          <h2><%= link_to follower.followee.email, profile_path(follower.followee) %></h2>

          <div class="well">
            <h3><%= follower.followee.tweets.last.text %></h3>
            tweeted on <%= follower.followee.tweets.last.created_at %>

          </div>
        </div>

      <% end %>

    </div>
  </div>
</div>